"""wheel spins

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 10:06:46.940233

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wheel_spins",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("spun_by_id", sa.Uuid(), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("result_index", sa.Integer(), nullable=False),
        sa.Column("result_activity_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", UTCDateTime(), nullable=True),
        sa.Column("accepted_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accepted_by_id"],
            ["users.id"],
            name=op.f("fk_wheel_spins_accepted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_wheel_spins_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result_activity_id"],
            ["activities.id"],
            name=op.f("fk_wheel_spins_result_activity_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spun_by_id"],
            ["users.id"],
            name=op.f("fk_wheel_spins_spun_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wheel_spins")),
    )
    with op.batch_alter_table("wheel_spins", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wheel_spins_accepted_by_id"), ["accepted_by_id"], unique=False
        )
        batch_op.create_index(
            "ix_wheel_spins_group_created", ["group_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wheel_spins_result_activity_id"), ["result_activity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_wheel_spins_spun_by_id"), ["spun_by_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wheel_spins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wheel_spins_spun_by_id"))
        batch_op.drop_index(batch_op.f("ix_wheel_spins_result_activity_id"))
        batch_op.drop_index("ix_wheel_spins_group_created")
        batch_op.drop_index(batch_op.f("ix_wheel_spins_accepted_by_id"))

    op.drop_table("wheel_spins")
    # ### end Alembic commands ###
