"""availability

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 20:15:13.878902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "slot",
            sa.Enum(
                "all_day",
                "morning",
                "afternoon",
                "evening",
                name="availabilityslot",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("free", "maybe", "busy", name="availabilitystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_availability_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability")),
        sa.UniqueConstraint("user_id", "date", "slot", name=op.f("uq_availability_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("availability")
    # ### end Alembic commands ###
