"""event occurrence overrides

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-27 14:07:13.260642

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_exceptions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cancelled", sa.Boolean(), server_default=sa.text("1"), nullable=False)
        )
        batch_op.add_column(sa.Column("override_title", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("override_starts_at", UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("override_ends_at", UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("override_start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("override_end_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # Edited occurrences can't be expressed without the columns: drop them rather than let them
    # turn into cancellations.
    op.execute("DELETE FROM event_exceptions WHERE cancelled = 0")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_exceptions", schema=None) as batch_op:
        batch_op.drop_column("override_end_date")
        batch_op.drop_column("override_start_date")
        batch_op.drop_column("override_ends_at")
        batch_op.drop_column("override_starts_at")
        batch_op.drop_column("override_title")
        batch_op.drop_column("cancelled")

    # ### end Alembic commands ###
