"""polls poll_options poll_votes

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 10:09:48.174212

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "polls",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.String(length=200), nullable=False),
        sa.Column("allow_multiple", sa.Boolean(), nullable=False),
        sa.Column("closes_at", UTCDateTime(), nullable=True),
        sa.Column("closed_at", UTCDateTime(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_polls_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_polls_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_polls_group_id_groups"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_polls")),
    )
    with op.batch_alter_table("polls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_polls_activity_id"), ["activity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_polls_created_by_id"), ["created_by_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_polls_group_id"), ["group_id"], unique=False)

    op.create_table(
        "poll_options",
        sa.Column("poll_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100, collation="NOCASE"), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_poll_options_added_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.id"],
            name=op.f("fk_poll_options_poll_id_polls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_options")),
        sa.UniqueConstraint("poll_id", "label", name=op.f("uq_poll_options_poll_id")),
    )
    with op.batch_alter_table("poll_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_poll_options_added_by_id"), ["added_by_id"], unique=False
        )

    op.create_table(
        "poll_votes",
        sa.Column("option_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("poll_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["poll_options.id"],
            name=op.f("fk_poll_votes_option_id_poll_options"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"], ["polls.id"], name=op.f("fk_poll_votes_poll_id_polls"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_poll_votes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("option_id", "user_id", name=op.f("pk_poll_votes")),
    )
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.create_index("ix_poll_votes_poll_user", ["poll_id", "user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_votes_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_votes_user_id"))
        batch_op.drop_index("ix_poll_votes_poll_user")

    op.drop_table("poll_votes")
    with op.batch_alter_table("poll_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_options_added_by_id"))

    op.drop_table("poll_options")
    with op.batch_alter_table("polls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_polls_group_id"))
        batch_op.drop_index(batch_op.f("ix_polls_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_polls_activity_id"))

    op.drop_table("polls")
    # ### end Alembic commands ###
