"""groups memberships invites group log

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 14:17:27.995836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("emoji", sa.String(length=16), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("members_can_invite", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_groups_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_groups_created_by_id"), ["created_by_id"], unique=False
        )

    op.create_table(
        "group_log",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_group_log_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_group_log_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_log")),
    )
    with op.batch_alter_table("group_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_group_log_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            "ix_group_log_group_action_created", ["group_id", "action", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_group_log_group_created", ["group_id", "created_at"], unique=False
        )

    op.create_table(
        "invites",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", UTCDateTime(), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("revoked_at", UTCDateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "max_uses IS NULL OR max_uses BETWEEN 1 AND 100", name=op.f("ck_invites_max_uses_range")
        ),
        sa.CheckConstraint(
            "max_uses IS NULL OR use_count <= max_uses", name=op.f("ck_invites_uses_within_max")
        ),
        sa.CheckConstraint("use_count >= 0", name=op.f("ck_invites_use_count_nonneg")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_invites_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_invites_group_id_groups"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("code", name=op.f("uq_invites_code")),
    )
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invites_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_invites_group_id"), ["group_id"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", name="role", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("show_birthday", sa.Boolean(), nullable=False),
        sa.Column("invite_id", sa.Uuid(), nullable=True),
        sa.Column("joined_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_memberships_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["invites.id"],
            name=op.f("fk_memberships_invite_id_invites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_memberships")),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_invite_id"), ["invite_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "uq_memberships_owner",
            ["group_id"],
            unique=True,
            sqlite_where=sa.text("role = 'owner'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index("uq_memberships_owner", sqlite_where=sa.text("role = 'owner'"))
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_invite_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invites_group_id"))
        batch_op.drop_index(batch_op.f("ix_invites_created_by_id"))

    op.drop_table("invites")
    with op.batch_alter_table("group_log", schema=None) as batch_op:
        batch_op.drop_index("ix_group_log_group_created")
        batch_op.drop_index("ix_group_log_group_action_created")
        batch_op.drop_index(batch_op.f("ix_group_log_actor_id"))

    op.drop_table("group_log")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_created_by_id"))

    op.drop_table("groups")
    # ### end Alembic commands ###
