"""events and event exceptions

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 10:18:00.601854

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "one_time", "recurring", "birthday", name="eventkind", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column("starts_at", UTCDateTime(), nullable=True),
        sa.Column("ends_at", UTCDateTime(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("rrule", sa.String(length=200), nullable=True),
        sa.Column("location_name", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("window_start", UTCDateTime(), nullable=False),
        sa.Column("window_end", UTCDateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "(kind = 'one_time') = (rrule IS NULL)", name=op.f("ck_events_kind_rrule")
        ),
        sa.CheckConstraint(
            "kind <> 'birthday' OR (all_day AND rrule = 'FREQ=YEARLY' AND end_date = start_date)",
            name=op.f("ck_events_birthday"),
        ),
        sa.CheckConstraint(
            "(all_day AND start_date IS NOT NULL AND end_date IS NOT NULL AND starts_at IS NULL AND ends_at IS NULL) OR (NOT all_day AND starts_at IS NOT NULL AND ends_at IS NOT NULL AND start_date IS NULL AND end_date IS NULL)",
            name=op.f("ck_events_timing"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_events_activity_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_events_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_events_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_events_group_id_groups"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_activity_id"), ["activity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_category_id"), ["category_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_events_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            "ix_events_group_window_end", ["group_id", "window_end"], unique=False
        )
        batch_op.create_index(
            "ix_events_group_window_start", ["group_id", "window_start"], unique=False
        )

    op.create_table(
        "event_exceptions",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_key", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_event_exceptions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_exceptions_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_exceptions")),
        sa.UniqueConstraint(
            "event_id", "occurrence_key", name=op.f("uq_event_exceptions_event_id")
        ),
    )
    with op.batch_alter_table("event_exceptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_exceptions_created_by_id"), ["created_by_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_exceptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_exceptions_created_by_id"))

    op.drop_table("event_exceptions")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_group_window_start")
        batch_op.drop_index("ix_events_group_window_end")
        batch_op.drop_index(batch_op.f("ix_events_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_events_category_id"))
        batch_op.drop_index(batch_op.f("ix_events_activity_id"))

    op.drop_table("events")
    # ### end Alembic commands ###
