"""categories activities activity interests

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 19:43:31.686408

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from friends_api.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=40, collation="NOCASE"), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("field_defs", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_categories_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_categories_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            "ix_categories_group_parent_position",
            ["group_id", "parent_id", "position"],
            unique=False,
        )
        batch_op.create_index(
            "uq_categories_sub_name",
            ["parent_id", "name"],
            unique=True,
            sqlite_where=sa.text("parent_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_categories_top_name",
            ["group_id", "name"],
            unique=True,
            sqlite_where=sa.text("parent_id IS NULL"),
        )

    op.create_table(
        "activities",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120, collation="NOCASE"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "idea",
                "planning",
                "scheduled",
                "done",
                "dropped",
                name="activitystatus",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("estimated_cost", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("cost_per_person", sa.Boolean(), nullable=False),
        sa.Column("location_name", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status_changed_at", UTCDateTime(), nullable=False),
        sa.Column("completed_at", UTCDateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "(estimated_cost IS NULL) = (currency IS NULL)",
            name=op.f("ck_activities_cost_currency"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost BETWEEN 0 AND 10000000",
            name=op.f("ck_activities_cost_range"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_activities_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_activities_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_activities_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_activities_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activities_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activities_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_index(
            "ix_activities_group_category", ["group_id", "category_id"], unique=False
        )
        batch_op.create_index(
            "ix_activities_group_due_date", ["group_id", "due_date"], unique=False
        )
        batch_op.create_index("ix_activities_group_owner", ["group_id", "owner_id"], unique=False)
        batch_op.create_index(
            "ix_activities_group_status_created", ["group_id", "status", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activities_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "activity_interests",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_interests_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_activity_interests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("activity_id", "user_id", name=op.f("pk_activity_interests")),
    )
    with op.batch_alter_table("activity_interests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_interests_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_interests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_interests_user_id"))

    op.drop_table("activity_interests")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_owner_id"))
        batch_op.drop_index("ix_activities_group_status_created")
        batch_op.drop_index("ix_activities_group_owner")
        batch_op.drop_index("ix_activities_group_due_date")
        batch_op.drop_index("ix_activities_group_category")
        batch_op.drop_index(batch_op.f("ix_activities_created_by_id"))
        batch_op.drop_index(batch_op.f("ix_activities_category_id"))

    op.drop_table("activities")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index("uq_categories_top_name", sqlite_where=sa.text("parent_id IS NULL"))
        batch_op.drop_index("uq_categories_sub_name", sqlite_where=sa.text("parent_id IS NOT NULL"))
        batch_op.drop_index("ix_categories_group_parent_position")
        batch_op.drop_index(batch_op.f("ix_categories_created_by_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
